module.exports =
{
    completed_successfully   : 'Successfully completed.',
    saved_successfully       : 'Successfully saved.',
    edited_successfully      : 'Successfully edited.',
    removed_successfully     : 'Successfully removed.',
    recover_successfully     : 'Successfully recovered.',
    recover_error            : 'An error occurred while trying to recover.',
    saved_error              : 'An error occurred while trying to save.',
    edited_error             : 'An error occurred while trying to edit.',
    removed_error            : 'Ocurri√≥ un error al intentar eliminar.',
    is_removed               : 'An error occurred while trying to delete.',
    is_missing               : 'This item is missing.',
    is_exist                 : 'This item already exists.',
    user_is_missing          : 'This user does not exist.',
	role_is_missing          : 'This charge does not exist.',
	permission_is_missing    : 'This permission does not exist.',
	new_password_not_match	 : 'Passwords do not match.',
	current_password_not_match: 'Current password does not match.',
    password_successfully    : 'Password updated successfully.',
    avatar_successfully      : 'Profile photo successfully updated.',
	logo_successfully        : 'Logo successfully updated.',
    email_already_use        : 'This email already in use.',
	name_already_use         : 'This name already in use.',
    bad_credentials          : 'Bad credentials.',
	cannot_removed_being_used: 'It cannot be removed because it is being used.',
	assigned_charges		 : 'Successfully assigned charges.',
	assigned_users			 : 'Successfully assigned users.'
}
